package com.fmt.fmt_backend.enums;

public enum ActivityType {
    CALL_ATTEMPTED,
    WHATSAPP_SENT,
    WHATSAPP_SEQUENCE,
    WHATSAPP_INBOUND,
    WHATSAPP_OUTBOUND,
    WHATSAPP_BOT_REPLIED,
    STATUS_CHANGE,
    NOTE_ADDED,
    LEAD_IMPORTED,
    FOLLOWUP_SCHEDULED,
    PAYMENT_RECORDED,
    WEBINAR_REGISTERED,
    WHATSAPP_CAMPAIGN
}
